# Generated by Django 6.0.6 on 2026-06-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_identifier', models.CharField(max_length=255, unique=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('file_size', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active_default', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
