# Generated by Django 6.0.6 on 2026-06-10 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_option_id', models.IntegerField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_FOR_NODE', 'Waiting For Node'), ('DISPATCHED_TO_NODE', 'Dispatched To Node'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=25)),
                ('processed_by_type', models.CharField(choices=[('CENTRAL_GPU', 'Central GPU'), ('USER_NODE', 'User Node'), ('UNASSIGNED', 'Unassigned')], default='UNASSIGNED', max_length=20)),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compute.usercomputenode')),
            ],
        ),
    ]
